# Generated by Django 2.0 on 2017-12-14 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web02', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='name',
        ),
    ]
