# Generated by Django 2.0 on 2018-01-01 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web02', '0003_auto_20171231_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='code',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='员工编号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='usertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web02.UserType', to_field='code', verbose_name='用户类型'),
        ),
    ]
